apiVersion: v1

kind: Service

metadata:
  name: api-service
  labels:
    app: api-app

spec:
  selector:
    app: api-app
  type: NodePort
  ports:   #if you have multiple port defined in a service , you have to name that port.[nana]
    - nodePort: 31002
      port: 8080  #service port is arbitrary
      targetPort: 8080   #container port must be equal to targetPort, container port defined in api-deploy.yaml file

