apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-app

  template:
    metadata:
      labels:
        app: api-app
    spec:
      containers:
        - name: api-container
          image: pranganmajumder/go-basic-restapi:1.0.4
          ports:
            - containerPort: 8080


