# https://www.youtube.com/watch?v=OZAhYSDkhsI

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: example

spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: example
              image: busybox:1.28
              args:
                - /bin/sh
                - -c
                - date
          restartPolicy: OnFailure

